name: publish
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Publish to Modrinth and CurseForge
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
        run: |
          ./gradlew publishUnified --no-daemon --info --stacktrace